dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

matrix:
  allow_failures:
    - python: "3.8-dev"

# command to install dependencies
install:
  - "pip install pipenv --upgrade-strategy=only-if-needed"
  - "pipenv install --dev"

# command to run the dependencies
script:
  - "pipenv run tests"

# command to run tests
# jobs:
  # include:
    # - stage: "✨ Flake8 Nit–Picking ✨"
      # python: "3.6"
      # script: "pipenv run flake8"

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: "<username>"
  password:
    secure: "<password>"
  on:
    tags: true
    branch: master
    repo: kennethreitz/requests-html
    python: "3.7"
